
[workspace]
members = ["journey-bot", "sea-entity", "sea-migration"]
resolver = "3"

[replace]
"serenity:0.12.4" = { git = "https://github.com/serenity-rs/serenity", rev = "b5ec750bd18b18592ad15d83bb6f9a4a9b6342da" }
