services:
  bot:
    image: ghcr.io/arckoor/journey-bot:latest
    build: .
    container_name: journey-bot
    restart: unless-stopped
    environment:
      - PYTHONPATH=/
    volumes:
      - ./config/master.json:/JourneyBot/config/master.json
      - ./config/links.json:/JourneyBot/config/links.json
      - log-data:/JourneyBot/logs
    depends_on:
      db:
        condition: service_healthy
    networks:
      - journey-bot-network
  db:
    image: postgres:16
    container_name: journey-bot-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: journey-bot
      POSTGRES_PASSWORD: ${PG_PASSWORD}
      POSTGRES_DB: journey-bot-db
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - journey-bot-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5


networks:
  journey-bot-network:
    driver: bridge

volumes:
  db-data:
  log-data:
