[package]
name = "sea-migration"
version = "0.1.0"
edition = "2024"
publish = false

[dependencies]
async-std = { version = "1.13.2", features = ["attributes", "tokio1"] }
sea-orm-migration = { version = "1.1.17", features = [
  "runtime-tokio-rustls",
  "sqlx-postgres",
] }
