//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel)]
#[sea_orm(table_name = "assigned_bypass_role")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub user_id: i64,
    #[sea_orm(column_type = "Double")]
    pub timestamp: f64,
    pub bypass_role_id: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::bypass_role::Entity",
        from = "Column::BypassRoleId",
        to = "super::bypass_role::Column::Id",
        on_update = "Cascade",
        on_delete = "Restrict"
    )]
    BypassRole,
}

impl Related<super::bypass_role::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::BypassRole.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
