//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "bypass_role")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: String,
    pub guild_id: i64,
    pub role_id: i64,
    pub channel_id: i64,
    pub timeout: i32,
    pub name: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::assigned_bypass_role::Entity")]
    AssignedBypassRole,
}

impl Related<super::assigned_bypass_role::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::AssignedBypassRole.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
