//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.16

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel)]
#[sea_orm(table_name = "posted_stream")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub message_id: i64,
    pub user_login: String,
    pub stream_observer_id: String,
    #[sea_orm(column_type = "Double")]
    pub created_at: f64,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::stream_observer::Entity",
        from = "Column::StreamObserverId",
        to = "super::stream_observer::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    StreamObserver,
}

impl Related<super::stream_observer::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::StreamObserver.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
