//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum, Copy)]
#[sea_orm(rs_type = "Enum", db_type = "Enum", enum_name = "punishment")]
pub enum Punishment {
    #[sea_orm(string_value = "mute")]
    Mute,
    #[sea_orm(string_value = "ban")]
    Ban,
}
