//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.16

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel)]
#[sea_orm(table_name = "staged_censor_item")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub item: String,
    pub foreign_id: String,
    #[sea_orm(column_type = "Double")]
    pub created_at: f64,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
