name: ci

permissions:
  contents: read

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

concurrency:
  group: ${{ github.workflow }} @ ${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        build-flags: ["", "--release"]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - run: cargo build ${{ matrix.build-flags }}

  build-nix:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: cachix/install-nix-action@v31
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}
      - uses: cachix/cachix-action@v16
        with:
          name: arckoor-cache
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
      - run: nix build
      - run: docker image load < result

  fmt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Install rustfmt
        run: rustup component add rustfmt
      - name: Format Check
        run: cargo fmt -- --check

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Lint Code
        run: cargo clippy -- -D warnings
